config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  get 'services/chart'
   get 'services/chart_mode'
  resources :services do
    collection do
      get 'chart1'
      get 'chart_mode_js'
    end
  end  

  resources :tecnics
  resources :service_modes
  resources :service_types
  resources :service_areas
  resources :repair_histories
  resources :repair_types
  resources :areas 
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :services
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/repair_history.rb
class RepairHistory < ApplicationRecord
  belongs_to :service_area
  belongs_to :tecnic
  belongs_to :repair_type
end

app/models/repair_type.rb
class RepairType < ApplicationRecord
	has_many :repair_histories
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :tecnic
  belongs_to :area
  belongs_to :service_area
  belongs_to :service_mode
  belongs_to :service_type
  scope :abc, ->(start_date, end_date) {
  where("services.date >= '#{start_date}' and services.date <= '#{end_date}'")
} 
end

app/models/service_area.rb
class ServiceArea < ApplicationRecord
	has_many :services
	has_many :repair_histories
end

app/models/service_mode.rb
class ServiceMode < ApplicationRecord
	has_many :services
	
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
	has_many :services
end

app/models/tecnic.rb
class Tecnic < ApplicationRecord
	
	has_many :repair_histories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  before_action :set_service_type, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  # GET /service_types
  # GET /service_types.json
  def index
    @service_types = ServiceType.all
  end

  # GET /service_types/1
  # GET /service_types/1.json
  def show
  end

  # GET /service_types/new
  def new
    @service_type = ServiceType.new
  end

  # GET /service_types/1/edit
  def edit
  end

  # POST /service_types
  # POST /service_types.json
  def create
    @service_type = ServiceType.new(service_type_params)

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to @service_type, notice: 'Service type was successfully created.' }
        format.json { render :show, status: :created, location: @service_type }
      else
        format.html { render :new }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_types/1
  # PATCH/PUT /service_types/1.json
  def update
    respond_to do |format|
      if @service_type.update(service_type_params)
        format.html { redirect_to @service_type, notice: 'Service type was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_type }
      else
        format.html { render :edit }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1
  # DELETE /service_types/1.json
  def destroy
    @service_type.destroy
    respond_to do |format|
      format.html { redirect_to service_types_url, notice: 'Service type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_type
      @service_type = ServiceType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_type_params
      params.require(:service_type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/repair_types_helper.rb
module RepairTypesHelper
end

app/helpers/service_areas_helper.rb
module ServiceAreasHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tecnics_helper.rb
module TecnicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/service_types/_form.html.erb
<%= form_with(model: service_type, local: true) do |form| %>
  <% if service_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_type.errors.count, "error") %> prohibited this service_type from being saved:</h2>

      <ul>
      <% service_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<h1>Editing Service Type</h1>

<%= render 'form', service_type: @service_type %>

<%= link_to 'Show', @service_type %> |
<%= link_to 'Back', service_types_path %>

app/views/service_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_types.each do |service_type| %>
      <tr>
        <td><%= service_type.name %></td>
        <td><%= link_to 'Show', service_type %></td>
        <td><%= link_to 'Edit', edit_service_type_path(service_type) %></td>
        <td><%= link_to 'Destroy', service_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Type', new_service_type_path %>

app/views/service_types/new.html.erb
<h1>New Service Type</h1>

<%= render 'form', service_type: @service_type %>

<%= link_to 'Back', service_types_path %>

app/views/service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_type.name %>
</p>

<%= link_to 'Edit', edit_service_type_path(@service_type) %> |
<%= link_to 'Back', service_types_path %>