config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  get 'services/chart'
   get 'services/chart_mode'
  resources :services do
    collection do
      get 'chart1'
      get 'chart_mode_js'
    end
  end  

  resources :tecnics
  resources :service_modes
  resources :service_types
  resources :service_areas
  resources :repair_histories
  resources :repair_types
  resources :areas 
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :services
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/repair_history.rb
class RepairHistory < ApplicationRecord
  belongs_to :service_area
  belongs_to :tecnic
  belongs_to :repair_type
end

app/models/repair_type.rb
class RepairType < ApplicationRecord
	has_many :repair_histories
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :tecnic
  belongs_to :area
  belongs_to :service_area
  belongs_to :service_mode
  belongs_to :service_type
  scope :abc, ->(start_date, end_date) {
  where("services.date >= '#{start_date}' and services.date <= '#{end_date}'")
} 
end

app/models/service_area.rb
class ServiceArea < ApplicationRecord
	has_many :services
	has_many :repair_histories
end

app/models/service_mode.rb
class ServiceMode < ApplicationRecord
	has_many :services
	
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
	has_many :services
end

app/models/tecnic.rb
class Tecnic < ApplicationRecord
	
	has_many :repair_histories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Evento creado correctamente' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :start, :end)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/repair_types_helper.rb
module RepairTypesHelper
end

app/helpers/service_areas_helper.rb
module ServiceAreasHelper
end

app/helpers/service_modes_helper.rb
module ServiceModesHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tecnics_helper.rb
module TecnicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/events/_form.html.erb
<div class="my-3 my-md-5">
          <div class="container">
            <div class="row">
              <div class="col-12">
              <%= form_for(@event,:html => {:class => 'card'}) do |form| %>
                  <div class="card-header">
                    <h3 class="card-title">Registro de Evento</h3>
                  </div>
                  <div class="card-body">
                    <div class="row">
             <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>         
 
<div class="col-xs-6 col-md-10"></div>


    <div class="col-12">
            <div class="form-group">
              <label class="form-label">Titulo del evento</label>
              <%= form.text_field :title, :class => 'form-control' %>

            </div></div>
<div class="col-12">
            <div class="form-group">
              <label class="form-label">Fecha de inicio de Evento</label>
              <%= form.text_field :start, id: :start, :value=>Date.today.strftime('%d/%m/%Y'),class: 'datepicker form-control'%>

            </div></div>
            <div class="col-12">
             <div class="form-group">
              <label class="form-label">Fecha de inicio de Evento</label>
              <%= form.text_field :end, id: :end, :value=>Date.today.strftime('%d/%m/%Y'),class: 'datepicker form-control'%>

            </div></div>

      
 
   </div>
   </div>
  <div class="card-footer text-right">
                  <div class="d-flex">
    
    <%= form.submit "Registrar" ,class: "btn btn-primary ml-auto"  %>

  </div>
                </div>
<% end %>
   </div>
  </div>
</div>
</div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="my-3 my-md-5">
          <div class="container">
          

  <div class="row row-cards">
              <div class="col-12">
                <div class="card">
                  <div class="card-header col-12">
                    <h3 class="card-title">Calendario de Eventos</h3>
                  </div>
                  <div class="card-body col-12">
                  <div id="calendar2">

</div>

 </div>
                </div>
             
              </div>
            
           
           
              
            </div>
          </div>
           </div>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>